### ISSUE TITLE
Set dropdown list position at certain time

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-time-picker#96] opened 2019-01-30 08:12 UTC
It would be useful to be able to set the value on which the dropdown list will open, to facilitate selection. For example, the user opens the dropdown and the list starts at 8:00, but he can still scroll up to select 3:00; a plus would be to be able to have the current position always at the current time.

**Comment by web-padawan** [comment] 2019-06-03 07:08
Closing as duplicate of #70

**Closed by web-padawan** 2019-06-03 07:08 UTC
